### PR TITLE
Updates to Command Line slide deck

### PR DESCRIPTION
**Pull request by PDegenPortnoy**
Replace images with more readable versions that also have the same directory structure
Fix styling issues that caused incorrect formatting

Note: this presentation has "workspace" for the name of the vagrant workspace, although it was called "vagrant" in the master and is called "railsbridge" in the documentation.  Shouldn't be a blocker. :-)

### CODE REVIEW

**Comment by mxie** [comment]
Hey @PeterDP - Can you update your master branch and then rebase? I think your changes here accidentally undid some stuff we recently did. Thanks!

**Comment by PDegenPortnoy** [comment]
Hi @mxie -- I had done that and blended the two versions.  

The images were updated with the "workspace" instructions and the demo is set-up to use that structure, so live demo and slides will match.  We can note that "workspace == vagrant" or "workspace == railsbridge" as needed.

I kept in things like the notes containing `dir_1, dir_2, and suggestotron`. 

Do you think that will be OK?

**Comment by PDegenPortnoy** [comment]
Oh, yeah, I accidentally left some trailing spaces  :-(

**Comment by decklin** [comment]
Hi Peter,

`/home/vagrant/workspace` is actually no longer in the VM at all. So I think any references to that should not be put back in. They won't work.

I tried to keep this deck (which is great!) understandable while updating the paths, but I definitely may have missed some things, so thanks for going over it again, but it needs to stay up to date with the 2016-06 VM.

**Comment by PDegenPortnoy** [comment]
Thanks for the clarification, Decklin.  I'll re-install the VM and try to get everything updated for tonight.

**Pull request merged**
