### PR TITLE
Style docs for Boston RailsBridge compatibility

### PR DESCRIPTION
**Pull request by jsteiner**
- Fix error with loading Rack::ShowExceptions
- Colored consoles to be black for bash and Ruby red for IRB
- Made header look like RailsBridge Boston header.

### CODE REVIEW

**Comment by jsteiner** [comment]
@drapergeek ping!

**Comment by jsteiner** [comment]
Unfortunately, I was unable to get dropdown's working in the header, and think that would be more of a time commitment than I have to give right now. To get the HTML into a syntax that would be conducive to copying bootstrap's styles would require fighting some of the Erector setup that is currently in place.

For now, the links go to the index pages for the respective resources.

**Comment by drapergeek** [comment]
Looks good to merge @jsteiner.

**Comment by jsteiner** [comment]
I don't have push access to this repo. Any chance somebody could merge this in?

**Pull request merged**
