### PR TITLE
add vm and irb instructions

### PR DESCRIPTION
**Pull request by Theaces**
I made the changes I suggested on your files

### CODE REVIEW

**Comment by decklin** [comment]
Thanks, we want to come up with a better style (probably using different colors and CSS content) for all text that students need to type in, so that everything doesn't need to include "press [Enter] or [Return]".

**Comment by Theaces** [comment]
Oh cool.

I was just writing you a letter to see if you needed help putting in the
contents.

Alice

On Sunday, September 21, 2014, Decklin Foster notifications@github.com
wrote:

> Thanks, we want to come up with a better style (probably using different
> colors and CSS content) for all text that students need to type in, so that
> everything doesn't need to include "press [Enter] or [Return]".
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/railsbridge-boston/docs/pull/22#issuecomment-56300569
> .

## 

Sent from mobile phone

**Comment by gabebw** [comment]
Thanks for the changes, Alice!

I've rebased this and re-opened as #35 so the changes apply cleanly, so I'm closing this.

**Comment by Theaces** [comment]
Cool

On Friday, December 5, 2014, Gabe Berke-Williams notifications@github.com
wrote:

> Closed #22 https://github.com/railsbridge-boston/docs/pull/22.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/railsbridge-boston/docs/pull/22#event-203414526.

## 

Sent from mobile phone

**Pull request closed without merging**
